config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'auth/:provider/callback', to: 'posts#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'posts#destroy', as: 'signout'

  resources :posts
  resource :static, only: [:show]

  root :to => 'static#homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  def self.create_from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.refresh_token = auth.credentials.refresh_token
      user.access_token = auth.credentials.access_token
      user.save!
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_user

  def contacts
    service = Youtube::PeopleServiceService.new
    service.authorization = secrets.to_authorization
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'yt'
  require 'google/apis'
  require 'google/apis/youtube_v3'
  require 'googleauth'
  require 'googleauth/stores/file_token_store'

  require 'fileutils'

  require 'net/http'
  require 'cgi'
  require 'certified'
  require 'httparty'
  require 'uri'

  def index

    Yt.configure do |config|
      config.api_key = "AIzaSyDiT_oxqFucNcolq6BeV2uLWhOP0P4gtOI"
      config.client_id = '393365834206-41sodsbcrq0pgft9sci3hj17masf8ib1.apps.googleusercontent.com'
      config.client_secret = 'rNytXXvaszqf_x1cb-F-DuN4'
      config.log_level = :debug
    end

    @account = Yt::Account.new(scopes: ["https://www.googleapis.com/auth/youtube, https://www.googleapis.com/auth/plus.login"], redirect_uri: 'localhost:3000').authentication_url



  end



end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  require 'json'
  def google_oauth2
    @user = User.create_from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MetaStreamTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render "shared/alerts" %>
  </head>

  <div class="container">
    <div class="row">
      <% if current_user %>
          Signed in as <strong><%= current_user.name %></strong>!
          <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
          <%= link_to "Sign in with Google", "/users/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
    <div>
      <%= yield %>
    </div>
    </div>
  </div>
</html>

app/views/posts/index.html.erb
<% require  'yt' %>

<%= render 'shared/nav' %>
<h2>
  This is the index
</h2>

<%= @account.id %>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_nav.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">

          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button> <a class="navbar-brand" href="#">MetaStream</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "All", posts_path %>
            </li>
            <li>
              <%= link_to "" %>
            </li>
            <li>
              <%= link_to ""%>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</div>